version: '2'

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/assignment-db
      - SPRING_DATASOURCE_USERNAME=assignment-postgres
      - SPRING_DATASOURCE_PASSWORD=assignment-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - "logstash:logstash"

  db:
    image: 'postgres:15.0-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=assignment-db
      - POSTGRES_USER=assignment-postgres
      - POSTGRES_PASSWORD=assignment-postgres
    ports:
      - "5432:5432"
    depends_on:
      - kibana
    links:
      - "logstash:logstash"

  filebeat:
    build:
      context: ./filebeat
    links:
      - "logstash:logstash"
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/app:/var/app

  logstash:
    build:
      context: ./logstash
    ports:
      - "5044:5044"
    volumes:
      - $HOME/app:/var/app
    links:
      - "elasticsearch:elasticsearch"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.8.7
    environment:
      - discovery.type=single-node
    volumes:
      - $HOME/app:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:6.8.7
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - "elasticsearch:elasticsearch"
    volumes:
      - $HOME/app:/var/app
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
