FROM openjdk:17-oracle
ARG JAR_FILE=../jar/*.jar
COPY ${JAR_FILE} application.jar
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n", "-jar", "application.jar"]